### PR TITLE
localconfig connector support for gemfire

### PR DESCRIPTION
**Pull request by eitansuez**
hello,
  i recently experimented with working with gemfire on pivotal cloud foundry, so this project was useful.  this pull request enables local development with the same code via the spring cloud localconfig connector.  that connector does not explicitly support gemfire.  this pull request adds it.
thanks,
/ eitan

### CODE REVIEW

**Comment by mavenraven** [comment]
@mkenyon @awmartin

**Comment by mkenyon** [comment]
@pulkitpivotal ?

**Comment by pulkitpivotal** [comment]
Thanks Eitan for the pull request. I will review.

**Comment by pulkitpivotal** [comment]
@eitansuez Looks pretty good, would you mind please adding a sample configuration in the README. E.g. if you can paste example properties which define the `gemfire://<IP>`.

**Comment by eitansuez** [comment]
check out the updated readme.  let me know if that works for you.  worse case, you can merge the pull request and edit the readme afterwards.  thanks! / eitan

**Comment by eitansuez** [comment]
clarification:  the readme i'm referring to is the one in the subfolder `spring-cloud-gemfire-localconfig-connector`

**Pull request merged**
